version: '3.9'
services:
  server:
    build: .
    ports:
      - "8080:8080"
    networks:
      - net
    depends_on:
      - "database"
    env_file: .env

  database:
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_secrets/db_pw
    ports:
      - '5432:5432'
    secrets:
      - db_secrets
    volumes: 
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - net

networks:
 net:
  driver: bridge

secrets:
    db_secrets:
      file: ./.secrets
